### PR TITLE
Thomas blur load

### PR DESCRIPTION
**Pull request by tombak98**
Testing blur loading image

### CODE REVIEW

**Comment by wliu080** [comment]
Into dev first right?

**Comment by tombak98** [comment]
> Into dev first right?

Ah yes… good catch! Fixed

**Comment by wliu080** [comment]
Looks good! We should look to do it for all the other big images too!

**Review by wliu080 — APPROVED** [review]

**Comment by wliu080** [comment]
Maybe we shouldn't call it blur image, since it seems like next/image has the prop `blurDataUrl`, if you do `placeholder="blur"` https://nextjs.org/docs/app/api-reference/components/image#placeholder

I'm also looking into vercel image optimization, but it seems like we need to use `next/image` so could try swap to that?

**Pull request merged**
